### ISSUE TITLE
the test on pretrained model is pretty good but those output imgs are black

### ISSUE THREAD

**Issue by FUTUREEEEEE** [YudeWang/semantic-segmentation-codebase#5]
![image](https://user-images.githubusercontent.com/52389798/111096292-28af1800-857a-11eb-8d00-f38fec0af9e3.png)
the test results looks very good but the output imgs are all black (most of the output img are small ,about 2k each)

![image](https://user-images.githubusercontent.com/52389798/111096379-55fbc600-857a-11eb-850c-2dd17df2e071.png)
should results looks like this? or i need to post-process them?

![image](https://user-images.githubusercontent.com/52389798/111096460-89d6eb80-857a-11eb-96e6-9a76b50a7861.png)

**Comment by YudeWang** [comment]
Hi @FUTUREEEEEE ,
Here is a function for visualization.
https://github.com/YudeWang/semantic-segmentation-codebase/blob/995b8fa9d6b08e3ff1f15a7aef2ce5445deaa834/lib/datasets/VOCDataset.py#L115
